### ISSUE TITLE
https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg#{FF_VER}.podspec

### ISSUE THREAD

**Issue by cctvbtv123456** [debugly/FFmpegTutorial#12]
大神你好：https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg#{FF_VER}.podspec  这地址都打不开

**Comment by debugly** [comment]
将 #{FF_VER} 替换成 4.3 就可以访问了：https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg4.3.podspec
FF_VER 是在 podfile 里定义的 ruby 变量，一般情况下你不用访问这个地址；

这个地址不保证一直可用，日后可能下掉，你也可以自行编译 ffmpeg，相关脚本在这个仓库：https://github.com/debugly/MRFFToolChainBuildShell
已经编译好的，我放到了这个仓库做了备份：https://github.com/debugly/MRFFToolChainPod
