### ISSUE TITLE
'libavutil/frame.h' file not found

### ISSUE THREAD

**Issue by wangxiaola** [debugly/FFmpegTutorial#16]
pod install 后 运行报错

**Comment by wangxiaola** [comment]
汗 解决了 必须clone下来 才行 直接下载 pod后 不行

**Comment by debugly** [comment]
没有这个限制，直接下载也是可以的；
确定 pod install 成功了吗？（pod install 时会自动从 github 下载预编译好的 ffmpeg libs）
