### ISSUE TITLE
'libswscale/swscale.h' file not found 

### ISSUE THREAD

**Issue by Whaiyan** [debugly/FFmpegTutorial#20]
'libavutil/version.h' file not found 'libswscale/swscale.h' file not found 'libavutil/frame.h' file not found  我pod install三次 直接下载和git clone 都是这个问题，找不到这三个头文件   以前的issues也看了  没看出怎么解决

**Comment by debugly** [comment]
如果运行 iOS 的demo 就这么安装：
```
cd FFmpegTutorial/Example/iOS
pod install
```

如果运行 macOS 的demo 就这么安装：
```
cd FFmpegTutorial/Example/macOS
pod install
```

把你 pod install 的日志发下我看看。

**Comment by Whaiyan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by debugly** [comment]
更新了安装 FFmpeg 依赖的脚本，拉取最新代码后，再次运行 pod install；如果看到

⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️  依赖库安装失败，请重新运行 pod install ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

则表明网络不太好，从github下载预编译库失败，需要重新 pod install。

**Comment by cppixocial** [comment]
> 更新了安装 FFmpeg 依赖的脚本，拉取最新代码后，再次运行 pod install；如果看到
> 
> ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️ 依赖库安装失败，请重新运行 pod install ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
> 
> 则表明网络不太好，从github下载预编译库失败，需要重新 pod install。
![image](https://github.com/debugly/FFmpegTutorial/assets/153265292/cebd5668-ec70-43b1-a723-f86469e64b1b)

我也有同样的问题，pod install 成功，编译项目提示提示找不到 ffmpeg 的库

看了下你的podspec 引入文件目录有问题，没有vendor目录，目前只有 build 目录
![image](https://github.com/debugly/FFmpegTutorial/assets/153265292/92842901-fc29-46c5-8b38-265629d45d74)

**Comment by debugly** [comment]
@cppixocial 感谢指正，最新代码修复了。
