### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by xlsd** [debugly/FFmpegTutorial#5]
相比上一篇 USEBITMAP 0 时的情况，是省去了把 CIImage 转 CGImageRef，再把 CGImageRef 转成 UIImage 的过程！我觉得性能上会好些，没想到的是 fps，CPU，GPU 都降了，内存增加了近两倍！这是什么鬼？
这里您清楚为什么内存和CPU都增加了吗？我现在和您遇到相同的疑问。

**Comment by debugly** [comment]
这个问题我没有去深入探究了，因为实际渲染的话，不会采用这个方式，只是举例可以这么渲染。
由于目前忙于重写这些教程，所以我会在整理到这一篇时去研究下。

**Comment by debugly** [comment]
> 相比上一篇 USEBITMAP 0 时的情况，是省去了把 CIImage 转 CGImageRef，再把 CGImageRef 转成 UIImage 的过程！我觉得性能上会好些，没想到的是 fps，CPU，GPU 都降了，内存增加了近两倍！这是什么鬼？
> 这里您清楚为什么内存和CPU都增加了吗？我现在和您遇到相同的疑问。

这个问题我没有去深入探究了，因为实际渲染的话，不会采用这个方式，只是举例可以这么渲染。
由于目前忙于重写这些教程，所以我会在整理到这一篇时去研究下。

**Comment by xlsd** [comment]
好的，支持你。如果探究到了原因，可以回复下哈。谢谢，我这边看到的是IOSurface的内存占用非常大，这个又和渲染直接相关，但是为什么IOSurface大还不晓得原因。

**Comment by HZHCoder1990** [comment]
我也正在学习博主的demo，我准备使用OpenGL来渲染一下看下效果。

**Comment by debugly** [comment]
教程完全重写了，没有那些老代码了，先关闭吧。
