### ISSUE TITLE
下载 MRFFmpegPod 出现报错

### ISSUE THREAD

**Issue by GE-GAO-ZHAO** [debugly/FFmpegTutorial#6]
下载 MRFFmpegPod 出现报错： curl: (22) The requested URL returned error: 502 Bad Gateway

**Comment by debugly** [comment]
打开 Example/iOS/Podfile 文件，检查下 MRFFmpegPod 库的下载地址是否正确：
pod 'MRFFmpegPod', :podspec => "https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg#{FF_3_4_7}.podspec"
最新代码是没有问题的，不知道你使用的是什么时候提交的代码？
