### ISSUE TITLE
新人求助，为什么找不到头文件 #import <FFmpegTutorial/FFVersionHelper.h>

### ISSUE THREAD

**Issue by evehal** [debugly/FFmpegTutorial#7]
#import <FFmpegTutorial/FFVersionHelper.h>这里提示找不到，pod我也安装了啊
qidong@bogon FFmpegTutorial-master % pod install --project-directory=Example/iOS
will install MRFFmpeg3.4.7
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

**Comment by debugly** [comment]
Sorry，最近没有时间更新了，刚看到问题；

正常来讲不应该有问题的，FFmpegTutorial 是个 Pod 库，他依赖了 FFmpeg 库，而 Demo 工程依赖了 FFmpegTutorial Pod 库；你 Cmd + b 编译下，然后看下这次编译具体报了什么错吧？然后我看看怎么回事。

**Comment by evehal** [comment]
谢谢谢谢，我重新下了一次，这次ok了
